In [25]:
import numpy as np

In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
arr[0]

1

In [28]:
arr[5]

6

In [29]:
arr[2]+arr[4]

8

In [30]:
arr[1:5]

array([2, 3, 4, 5])

In [31]:
arr[-3:-1]

array([6, 7])

In [32]:
arr.dtype

dtype('int32')

In [33]:
x = arr.copy()

In [34]:
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
x[0] = 21
x

array([21,  2,  3,  4,  5,  6,  7,  8])

In [36]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
y = arr.view()
y

array([1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
y[0] = 11
y

array([11,  2,  3,  4,  5,  6,  7,  8])

In [39]:
arr

array([11,  2,  3,  4,  5,  6,  7,  8])

In [40]:
arr.shape

(8,)

In [41]:
arr.reshape(1,8)

array([[11,  2,  3,  4,  5,  6,  7,  8]])

In [42]:
arr

array([11,  2,  3,  4,  5,  6,  7,  8])

In [43]:
arr1 = np.array([11, 12, 32, 14, 15, 62, 63, 55])
arr1

array([11, 12, 32, 14, 15, 62, 63, 55])

In [44]:
arr2 = arr + arr1
arr2

array([22, 14, 35, 18, 20, 68, 70, 63])

In [45]:
array = np.concatenate((arr, arr1))
array

array([11,  2,  3,  4,  5,  6,  7,  8, 11, 12, 32, 14, 15, 62, 63, 55])

In [46]:
new_array = np.array_split(array, 5)
new_array

[array([11,  2,  3,  4]),
 array([5, 6, 7]),
 array([ 8, 11, 12]),
 array([32, 14, 15]),
 array([62, 63, 55])]

In [47]:
i = np.where(array == 11)
i

(array([0, 8], dtype=int64),)

In [48]:
np.sort(array)

array([ 2,  3,  4,  5,  6,  7,  8, 11, 11, 12, 14, 15, 32, 55, 62, 63])